#!/usr/bin/env python


keywords = dict({
'UTL_INADDR.GET_HOST_ADDRESS': 'f',

# http://blog.red-database-security.com/2009/01/17/tutorial-oracle-sql-injection-in-webapps-part-i/print/
'DBMS_PIPE.RECEIVE_MESSAGE':   'f',
'CTXSYS.DRITHSX.SN': 'f',
'SYS.STRAGG': 'f',
'ABS'                         : 'f',
'ACCESSIBLE'                  : 'k',
'ACOS'                        : 'f',
'ADD'                         : 'k',
'ADDDATE'                     : 'f',
'ADDTIME'                     : 'f',
'AES_DECRYPT'                 : 'f',
'AES_ENCRYPT'                 : 'f',
'AGAINST'                     : 'k',
'ALTER'                       : 'k',
'ALL_USERS'                   : 'k', # oracle
'ANALYZE'                     : 'k',
'AND'                         : 'o',
'AS'                          : 'k',
'ASC'                         : 'k',
'ASCII'                       : 'f',
'ASENSITIVE'                  : 'k',
'ASIN'                        : 'f',
'ATAN'                        : 'f',
'ATAN2'                       : 'f',
'AVG'                         : 'f',
'BEFORE'                      : 'k',
'BEGIN'                       : 'k',
'BENCHMARK'                   : 'f',
'BETWEEN'                     : 'k',
'BIGINT'                      : 'k',
'BINARY'                      : 'k',
'BINBINARY'                   : 'f',
'BIT_AND'                     : 'f',
'BIT_COUNT'                   : 'f',
'BIT_LENGTH'                  : 'f',
'BIT_OR'                      : 'f',
'BIT_XOR'                     : 'f',
'BLOB'                        : 'k',
'BOOLEAN'                     : 'k',
'BOTH'                        : 'k',
'BY'                          : 'n',
'CALL'                        : 'k',
'CASCADE'                     : 'k',
'CASE'                        : 'o',
'CAST'                        : 'f',
'CEIL'                        : 'f',
'CEILING'                     : 'f',
'CHANGE'                      : 'k',
# sometimes a function too
'CHAR'                        : 'k',

'CHARACTER'                   : 'k',
'CHARACTER_LENGTH'            : 'f',
'CHARSET'                     : 'f',
'CHAR_LENGTH'                 : 'f',
'CHECK'                       : 'k',
'CHR'                         : 'f',
'COALESCE'                    : 'k',
'COERCIBILITY'                : 'f',
'COLLATE'                     : 'k',
'COLLATION'                   : 'f',
'COLUMN'                      : 'k',
'COMPRESS'                    : 'f',
'CONCAT'                      : 'f',
'CONCAT_WS'                   : 'f',
'CONDITION'                   : 'k',
'CONNECTION_ID'               : 'f',
'CONSTRAINT'                  : 'k',
'CONTINUE'                    : 'k',
'CONV'                        : 'f',
'CONVERT'                     : 'f',
'CONVERT_TZ'                  : 'f',
'COS'                         : 'f',
'COT'                         : 'f',
'COUNT'                       : 'f',
'CRC32'                       : 'f',
'CREATE'                      : 'k',
'CURDATE'                     : 'f',
'CURRENT_DATE'                : 'k',
'CURRENT_DATECURRENT_TIME'    : 'f',
'CURRENT_TIME'                : 'k',
'CURRENT_TIMESTAMP'           : 'k',
'CURRENT_USER'                : 'k',
'CURSOR'                      : 'k',
'CURTIME'                     : 'f',
'DATABASE'                    : 'k',
'DATABASES'                   : 'k',
'DATE'                        : 'f',
'DATEDIFF'                    : 'f',
'DATE_ADD'                    : 'f',
'DATE_FORMAT'                 : 'f',
'DATE_SUB'                    : 'f',
'DAY'                         : 'f',
'DAYNAME'                     : 'f',
'DAYOFMONTH'                  : 'f',
'DAYOFWEEK'                   : 'f',
'DAYOFYEAR'                   : 'f',
'DAY_HOUR'                    : 'k',
'DAY_MICROSECOND'             : 'k',
'DAY_MINUTE'                  : 'k',
'DAY_SECOND'                  : 'k',
'DEC'                         : 'k',
'DECIMAL'                     : 'k',
'DECLARE'                     : 'k',
'DECODE'                      : 'f',
'DEFAULT'                     : 'k',
'DEGREES'                     : 'f',
'DELAY'                       : 'k',
'DELAYED'                     : 'k',
'DELETE'                      : 'k',
'DESC'                        : 'k',
'DESCRIBE'                    : 'k',
'DES_DECRYPT'                 : 'f',
'DES_ENCRYPT'                 : 'f',
'DETERMINISTIC'               : 'k',
'DISTINCROW'                  : 'k',
'DISTINCT'                    : 'k',
'DIV'                         : 'o',
'DROP'                        : 'k',
'DUAL'                        : 'k',
'EACH'                        : 'k',
'ELSE'                        : 'k',
'ELSEIF'                      : 'k',
'ELT'                         : 'f',
'ENCLOSED'                    : 'k',
'ENCODE'                      : 'f',
'ENCRYPT'                     : 'f',
'ESCAPED'                     : 'k',
# TBD
#'END'                         : 'k',
'EXEC'                        : 'k',   # mssql
'EXECUTE'                     : 'k',
'EXISTS'                      : 'k',
'EXIT'                        : 'k',
'EXP'                         : 'f',
'EXPLAIN'                     : 'k',
'EXPORT_SET'                  : 'f',
'EXTRACT'                     : 'f',
'EXTRACTVALUE'                : 'f',
'EXTRACT_VALUE'               : 'f',
'FALSE'                       : 'k',
'FETCH'                       : 'k',
'FIELD'                       : 'f',
'FIND_IN_SET'                 : 'f',
'FLOOR'                       : 'f',
'FORCE'                       : 'k',
'FOREIGN'                     : 'k',
'FOR'                         : 'n',
'FORMAT'                      : 'f',
'FOUND_ROWS'                  : 'f',
'FROM'                        : 'k',
'FROM_DAYS'                   : 'f',
'FROM_UNIXTIME'               : 'f',
'FULLTEXT'                    : 'k',
'GENERATE_SERIES'             : 'f',
'GET_FORMAT'                  : 'f',
'GET_LOCK'                    : 'f',
'GOTO'                        : 'k',
'GRANT'                       : 'k',
'GREATEST'                    : 'f',
'GROUP'                       : 'n',
'GROUP_CONCAT'                : 'f',
'HAVING'                      : 'k',  # MSSQL
'HEX'                         : 'f',
'HIGH_PRIORITY'               : 'k',
'HOUR'                        : 'f',
'HOUR_MICROSECOND'            : 'k',
'HOUR_MINUTE'                 : 'k',
'HOUR_SECOND'                 : 'k',
'HOST_NAME'                   : 'f',  # unknown DB
# if is normally a function, except in TSQL
# http://msdn.microsoft.com/en-us/library/ms182717.aspx
'IF'                          : 'k',
'IFF'                         : 'f',
'IFNULL'                      : 'f',
'IGNORE'                      : 'k',
'IIF'                         : 'f',

# IN is a special case.. sometimes a function, sometimes a keyword
'IN'                          : 'n',

'INDEX'                       : 'k',
'INET_ATON'                   : 'f',
'INET_NTOA'                   : 'f',
'INFILE'                      : 'k',
'INNER'                       : 'k',
'INOUT'                       : 'k',
'INSENSITIVE'                 : 'k',
'INSERT'                      : 'k',
'INSTR'                       : 'f',
'INT'                         : 'k',
'INT1'                        : 'k',
'INT2'                        : 'k',
'INT3'                        : 'k',
'INT4'                        : 'k',
'INT8'                        : 'k',
'INTEGER'                     : 'k',
'INTERVAL'                    : 'k',
'INTO'                        : 'k',
'IS'                          : 'o',
'ISNULL'                      : 'f',
'IS_FREE_LOCK'                : 'f',
'IS_MEMBER'                   : 'f',  # MSSQL
'IS_SRVROLEMEMBER'            : 'f',  # MSSQL
'IS_USED_LOCK'                : 'f',
'ITERATE'                     : 'k',
'JOIN'                        : 'k',
'KEYS'                        : 'k',
'KILL'                        : 'k',
'LAST_INSERT_ID'              : 'f',
'LCASE'                       : 'f',
'LEADING'                     : 'k',
'LEAST'                       : 'f',
'LEAVE'                       : 'k',
'LEFT'                        : 'f',
'LENGTH'                      : 'f',
'LIKE'                        : 'o',
'LIMIT'                       : 'k',
'LINEAR'                      : 'k',
'LINES'                       : 'k',
'LN'                          : 'f',
'LOAD'                        : 'k',
'LOAD_FILE'                   : 'f',
'LOCALTIME'                   : 'k',
'LOCALTIMESTAMP'              : 'k',
'LOCATE'                      : 'f',
'LOCK'                        : 'k',
'LOG'                         : 'f',
'LOG10'                       : 'f',
'LOG2'                        : 'f',
'LONGBLOB'                    : 'k',
'LONGTEXT'                    : 'k',
'LOOP'                        : 'k',
'LOWER'                       : 'f',
'LOW_PRIORITY'                : 'k',
'LPAD'                        : 'f',
'LTRIM'                       : 'f',
'MAKEDATE'                    : 'f',
'MAKE_SET'                    : 'f',
'MASTER_BIND'                 : 'k',
'MASTER_POS_WAIT'             : 'f',
'MASTER_SSL_VERIFY_SERVER_CERT': 'k',
'MATCH'                       : 'k',
'MAX'                         : 'f',
'MAXVALUE'                    : 'k',
'MD5'                         : 'f',
'MEDIUMBLOB'                  : 'k',
'MEDIUMINT'                   : 'k',
'MEDIUMTEXT'                  : 'k',
'MERGE'                       : 'k',
'MICROSECOND'                 : 'f',
'MID'                         : 'f',
'MIDDLEINT'                   : 'k',
'MIN'                         : 'f',
'MINUTE'                      : 'f',
'MINUTE_MICROSECOND'          : 'k',
'MINUTE_SECOND'               : 'k',
'MOD'                         : 'o',
'MODE'                        : 'n',
'MODIFIES'                    : 'k',
'MONTH'                       : 'f',
'MONTHNAME'                   : 'f',
'NAME_CONST'                  : 'f',
'NOT'                         : 'o',
'NOW'                         : 'f',
'NO_WRITE_TO_BINLOG'          : 'k',
'NULL'                        : '1',
'NULLIF'                      : 'f',
'NUMERIC'                     : 'k',
'OCT'                         : 'f',
'OCTET_LENGTH'                : 'f',
'OFFSET'                      : 'k',
'OLD_PASSWORD'                : 'f',
# need to investigate how used
#'ON'                          : 'k',
'ONE_SHOT'                    : 'k',
# obviously not SQL but used in attacks
'OWN3D'                       : 'k',
'OPEN'                        : 'k', # http://msdn.microsoft.com/en-us/library/ms190500.aspx
'OPENDATASOURCE'              : 'f', # http://msdn.microsoft.com/en-us/library/ms179856.aspx
'OPENXML'                     : 'f',
'OPENQUERY'                   : 'f',
'OPENROWSET'                  : 'f',
'OPTIMIZE'                    : 'k',
'OPTION'                      : 'k',
'OPTIONALLY'                  : 'k',
'OR'                          : 'o',
'ORD'                         : 'f',
'ORDER'                       : 'n',
'OUT'                         : 'k',
'OUTFILE'                     : 'k',
'PARTITION'                   : 'k',
'PASSWORD'                    : 'k',  # keyword "SET PASSWORD", and a function
'PERIOD_ADD'                  : 'f',
'PERIOID_DIFF'                : 'f',
'PG_SLEEP'                    : 'f',
'PI'                          : 'f',
'POSITION'                    : 'f',
'POW'                         : 'f',
'POWER'                       : 'f',
'PRECISION'                   : 'k',
'PRIMARY'                     : 'k',
'PROCEDURE'                   : 'k',
'PURGE'                       : 'k',
'QUARTER'                     : 'f',
'QUOTE'                       : 'f',
'RADIANS'                     : 'f',
'RAND'                        : 'f',
'RANDOMBLOB'                  : 'f',  # sqlite3
'RANGE'                       : 'k',
'READ'                        : 'k',
'READS'                       : 'k',
'READ_WRITE'                  : 'k',
'REAL'                        : 'n',   # only used in data definition
'REFERENCES'                  : 'k',
'REGEXP'                      : 'o',
'RELEASE'                     : 'k',
'RELEASE_LOCK'                : 'f',
'RENAME'                      : 'k',
'REPEAT'                      : 'k',
'REPLACE'                     : 'k',
'REQUIRE'                     : 'k',
'RESIGNAL'                    : 'k',
'RESTRICT'                    : 'k',
'RETURN'                      : 'k',
'REVERSE'                     : 'f',
'REVOKE'                      : 'k',
'RIGHT'                       : 'f',
'RLIKE'                       : 'o',
'ROUND'                       : 'f',
'ROW'                         : 'f',
'ROW_COUNT'                   : 'f',
'RPAD'                        : 'f',
'RTRIM'                       : 'f',
'SCHEMA'                      : 'k',
'SCHEMAS'                     : 'k',
'SECOND_MICROSECOND'          : 'k',
'SEC_TO_TIME'                 : 'f',
'SELECT'                      : 'k',
'SENSITIVE'                   : 'k',
'SEPARATOR'                   : 'k',
'SESSION_USER'                : 'f',
'SET'                         : 'k',
'SHA'                         : 'f',
'SHA1'                        : 'f',
'SHA2'                        : 'f',
'SHOW'                        : 'k',
'SHUTDOWN'                    : 'k',
'SIGN'                        : 'f',
'SIGNAL'                      : 'k',
'SIMILAR'                     : 'k',
'SIN'                         : 'f',
'SLEEP'                       : 'f',
'SMALLINT'                    : 'k',
'SOUNDEX'                     : 'f',
'SOUNDS'                      : 'o',
'SPACE'                       : 'f',
'SPATIAL'                     : 'k',
'SPECIFIC'                    : 'k',
'SQL'                         : 'k',
'SQLEXCEPTION'                : 'k',
'SQLSTATE'                    : 'k',
'SQLWARNING'                  : 'k',
'SQL_BIG_RESULT'              : 'k',
'SQL_CALC_FOUND_ROWS'         : 'k',
'SQL_SMALL_RESULT'            : 'k',
'SQRT'                        : 'f',
'SSL'                         : 'k',
'STARTING'                    : 'k',
'STDDEV'                      : 'f',
'STDDEV_POP'                  : 'f',
'STDDEV_SAMP'                 : 'f',
'STRAIGHT_JOIN'               : 'k',
'STRCMP'                      : 'f',
'STR_TO_DATE'                 : 'f',
'SUBDATE'                     : 'f',
'SUBSTR'                      : 'f',
'SUBSTRING'                   : 'f',
'SUBSTRING_INDEX'             : 'f',
'SUBTIME'                     : 'f',
'SUM'                         : 'f',
'SYSDATE'                     : 'f',
'SYSCOLUMNS'                  : 'k',  # http://msdn.microsoft.com/en-us/library/aa260398(v=sql.80).aspx
'SYSOBJECTS'                  : 'k',  # http://msdn.microsoft.com/en-us/library/aa260447(v=sql.80).aspx
'SYSUSERS'                    : 'k',  # MSSQL
'SYSTEM_USER'                 : 'f',
'TABLE'                       : 'k',
'TAN'                         : 'f',
'TERMINATED'                  : 'k',
'THEN'                        : 'k',
'TIME'                        : 'k',
'TIMEDIFF'                    : 'f',
'TIMESTAMP'                   : 'f',
'TIMESTAMPADD'                : 'f',
'TIME_FORMAT'                 : 'f',
'TIME_TO_SEC'                 : 'f',
'TINYBLOB'                    : 'k',
'TINYINT'                     : 'k',
'TINYTEXT'                    : 'k',
'TO_DAYS'                     : 'f',
'TO_SECONDS'                  : 'f',
'TRAILING'                    : 'k',
'TRIGGER'                     : 'k',
'TRIM'                        : 'f',
'TRUE'                        : 'k',
'TRUNCATE'                    : 'f',
'UCASE'                       : 'f',
'UNCOMPRESS'                  : 'f',
'UNCOMPRESS_LENGTH'           : 'f',
'UNDO'                        : 'k',
'UNHEX'                       : 'f',
'UNION'                       : 'o',
# only used as a function (DB2) or as "CREATE UNIQUE"
'UNIQUE'                      : 'n',
'UNIX_TIMESTAMP'              : 'f',
'UNLOCK'                      : 'k',
'UNSIGNED'                    : 'k',
'UPDATE'                      : 'k',
'UPDATEXML'                   : 'f',
'UPPER'                       : 'f',
'USAGE'                       : 'k',
'USE'                         : 'k',
#'USER'                       : 'k',   # MySQL function?
'USING'                       : 'f',
'UTC_DATE'                    : 'k',
'UTC_TIME'                    : 'k',
'UTC_TIMESTAMP'               : 'k',
'UUID'                        : 'f',
'UUID_SHORT'                  : 'f',
'VALUES'                      : 'k',
'VARBINARY'                   : 'k',
'VARCHAR'                     : 'k',
'VARCHARACTER'                : 'k',
'VARIANCE'                    : 'f',
'VARYING'                     : 'k',
'VAR_POP'                     : 'f',
'VAR_SAMP'                    : 'f',
'VERSION'                     : 'f',
'WAITFOR'                     : 'k',
'WEEK'                        : 'f',
'WEEKDAY'                     : 'f',
'WEEKOFYEAR'                  : 'f',
'WHEN'                        : 'k',
'WHERE'                       : 'k',
'WHILE'                       : 'k',
'WITH'                        : 'k',
'XMLELEMENT'                  : 'f',   # oracle
'XMLFOREST'                   : 'f',   # oracle
'XMLFORMAT'                   : 'f',   # oracle
'XMLTYPE'                     : 'f',
'XOR'                         : 'o',
'XP_EXECRESULTSET'            : 'k',
'YEAR'                        : 'f',
'YEARWEEK'                    : 'f',
'YEAR_MONTH'                  : 'k',
'ZEROFILL'                    : 'k'
})

mapping = ['', '(', ')', ',', '1', ';', 'c', 'f', 'k', 'n', 'o', 's', 'v']


sqlipat = frozenset([
    '1)()s',
    '1))))',
    '1)));',
    '1)))k',
    '1)))o',
    '1));k',
    '1))k1',
    '1))kk',
    '1))o(',
    '1))o1',
    '1))of',
    '1))ok',
    '1))on',
    '1))oo',
    '1),(1',
    '1);k(',
    '1);kf',
    '1);kk',
    '1);kn',
    '1);ko',
    '1)k1',
    '1)k1c',
    '1)k1o',
    '1)kks',
    '1)o(1',
    '1)o(k',
    '1)o(n',
    '1)o1f',
    '1)o1k',
    '1)o1o',
    '1)of(',
    '1)ok(',
    '1)ok1',
    '1)ono',
    '1)oo(',
    '1,(f(',
    '1,(k(',
    '1,(k1',
    '1,(kf',
    '1,1),',
    '1,f(1',
    '1,s),',
    '1;k((',
    '1;k(1',
    '1;k(o',
    '1;kf(',
    '1;kks',
    '1;kn(',
    '1;knc',
    '1;ko(',
    '1;kok',
    '1k1',
    '1k1c',
    '1kf(1',
    '1kk(1',
    '1kksc',
    '1o(((',
    '1o((1',
    '1o((f',
    '1o(1)',
    '1o(1o',
    '1o(f(',
    '1o(k1',
    '1o(kf',
    '1o(kn',
    '1o(n)',
    '1o(s)',
    '1o1)o',
    '1o1f(',
    '1o1kf',
    '1o1o(',
    '1o1o1',
    '1o1of',
    '1o1ok',
    '1o1on',
    '1o1oo',
    '1o1ov',
    '1of()',
    '1of(1',
    '1of(f',
    '1of(n',
    '1ok',
    '1ok(1',
    '1ok(k',
    '1ok1',
    '1ok1,',
    '1ok1c',
    '1ok1k',
    '1okf(',
    '1oks,',
    '1oksc',
    '1okv,',
    '1ono1',
    '1onos',
    '1oo(1',
    '1oo1o',
    '1oso1',
    ';kknc',
    'f()of',
    'f(1)o',
    'f(1,f',
    'f(1o1',
    'f(f()',
    'f(f(1',
    'f(k()',
    'f(k,(',
    'f(n()',
    'f(v,1',
    'k()ok',
#    'k(k,(',
    'k(ok(',
    'k(vv)',
    'k1,1,',
    'k1,1k',
    'k1k(k',
    'k1o(s',
    'kf(1)',
    'kf(1,',
    'kf(f(',
    'kf(n,',
    'kvk(1',
    'n)));',
    'n)))k',
    'n)))o',
    'n));k',
    'n))kk',
    'n))o(',
    'n))o1',
    'n))of',
    'n))ok',
    'n);k(',
    'n);kf',
    'n);kk',
    'n);kn',
    'n);ko',
    'n)k1o',
    'n)kks',
    'n)o(k',
    'n)o1f',
    'n)o1o',
    'n)of(',
    'n)ok(',
    'n,(f(',
    'n,(k(',
    'n,(k1',
    'n,(kf',
    'n,f(1',
    'n;k((',
    'n;k(1',
    'n;kf(',
    'n;kks',
    'n;kn(',
    'n;ko(',
    'n;kok',
    'nkksc',
    'no(1)',
    'no(k1',
    'no1f(',
    'no1o(',
    'no1o1',
    'no1of',
    'nof(1',
    'nok(1',
    'nok(k',
    'noo1o',
    'of()o',
    'of(1)',
#    'of(1o',
    'ok1o1',
    'okkkn',
    'oo1kf',
    's)));',
    's)))k',
    's)))o',
    's));k',
    's))k1',
    's))kk',
    's))o(',
    's))o1',
    's))of',
    's))ok',
    's))oo',
    's),(1',
    's);k(',
    's);kf',
    's);kk',
    's);kn',
    's);ko',
    's)k1',
    's)k1c',
    's)k1o',
    's)kks',
    's)o(k',
    's)o1f',
    's)o1k',
    's)o1o',
    's)of(',
    's)ok(',
    's)ok1',
    's)oo(',
    's,1),',
    's;k((',
    's;k(1',
    's;k(o',
    's;k1,',
    's;k1o',
    's;k;',
    's;k[k',
    's;k[n',
    's;kf(',
    's;kkn',
    's;kks',
    's;kn(',
    's;knc',
    's;knk',
    's;knn',
    's;ko(',
    's;kok',
    's;n:k',
#    'sc',
    'sf(1)',
    'sf(n,',
    'sf(s)',
    'sk);k',
    'sk)k1',
    'sk)kk',
    'sk)o(',
    'sk)o1',
    'sk)of',
    'sk)ok',
    'sk1',
    'sk1c',
    'sk1o1',
    'sk1os',
    'skks',
    'skksc',
#    'sko(1',
#    'sko(k',
    'so(((',
    'so((k',
    'so((s',
    'so(1)',
    'so(1o',
    'so(f(',
    'so(k)',
    'so(k1',
    'so(kk',
    'so(kn',
    'so(ko',
    'so(ks',
    'so(s)',
    'so1c',
    'so1f(',
    'so1kf',
    'so1o(',
    'so1o1',
    'so1of',
    'so1ok',
#    'so1on',
    'so1oo',
    'so1os',
    'so1ov',
    'sof()',
    'sof(1',
    'sof(f',
    'sof(k',
    'sok(1',
    'sok(k',
    'sok(o',
    'sok(s',
    'sok1',
    'sok1,',
    'sok1c',
    'sok1o',
    'sokc',
    'sokf(',
#    'sokn,',
    'soknk',
    'soko(',
    'soko1',
    'sokok',
    'sokoo',
    'sokos',
    'son:o',
    'sono1',
    'sonos',
    'soo(1',
    'soo(k',
    'soo(o',
    'soo1o',
    'soof(',
    'sookc',
    'sos',
    'sosos',
    'sovo1',
    'sovok',
    'sovoo',
    'sovos',
    'sovov',
    'vok1,',
    's;kvk',
    'soso(',
    'sokn,',
    's)o(1',
    'o1kf(',
    'sovso',
    'sonk1',
    'sov:o',
    'ook1,',
    's;kvc',
    'no(o1',
    'so(os'
])

        # special in that single char is a valid operator
        # special case in that '<=' might also be '<=>'
        # ":" isn't an operator in mysql, but other dialects
        #   use it.
double_char_operators = frozenset( (
                '!=',   # oracle
                '||',
                '&&',
                '>=',
                '>>',
                '<=',
                '<>',
                ':=',
                '<<',
                '!<', # http://msdn.microsoft.com/en-us/library/ms188074.aspx
                '!>', # http://msdn.microsoft.com/en-us/library/ms188074.aspx
                '+=',
                '-=',
                '*=',
                '/=',
                '%=',
                '|=',
                '&=',
                '^=',
                '|/', # http://www.postgresql.org/docs/9.1/static/functions-math.html
                '!!', # http://www.postgresql.org/docs/9.1/static/functions-math.html
                '~*', # http://www.postgresql.org/docs/9.1/static/functions-matching.html
                '!~', # http://www.postgresql.org/docs/9.1/static/functions-matching.html
                '@>',
                '<@'
                # '!~*'
                ) )

CHAR_WORD = 0
CHAR_NONE = 1
CHAR_WHITE = 2
CHAR_STR = 3
CHAR_OP1 = 4
CHAR_OP2 = 5
CHAR_CHAR = 6
CHAR_COM1 = 7
CHAR_DASH = 8
CHAR_SLASH = 9
CHAR_BACK = 10
CHAR_NUM = 11
CHAR_VAR = 13
charmap = [
            CHAR_WHITE, # 0
            CHAR_WHITE, # 1
            CHAR_WHITE, # 2
            CHAR_WHITE, # 3
            CHAR_WHITE, # 4
            CHAR_WHITE, # 5
            CHAR_WHITE, # 6
            CHAR_WHITE, # 7
            CHAR_WHITE, # 8
            CHAR_WHITE, # 9
            CHAR_WHITE, # 10
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE, # 20
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_WHITE, #30
            CHAR_WHITE,
            CHAR_WHITE,
            CHAR_OP2,   # 33 !
            CHAR_STR,   # 34 "
            CHAR_COM1,  # "#"
            CHAR_WORD,  # $
            CHAR_OP1,   # %
            CHAR_OP2,   # &
            CHAR_STR,   # 39 '
            CHAR_CHAR,  # 40 (
            CHAR_CHAR,  # 41
            CHAR_OP2,   # 42 *
            CHAR_OP1,   # 43 +
            CHAR_CHAR,  # ,
            CHAR_DASH,
            CHAR_NUM,   # .
            CHAR_SLASH,
            CHAR_NUM,  # 0
            CHAR_NUM,   # 1
            CHAR_NUM,   # 2
            CHAR_NUM,   # 3
            CHAR_NUM,   # 4
            CHAR_NUM,   # 5
            CHAR_NUM,   # 6
            CHAR_NUM,   # 7
            CHAR_NUM,   # 8
            CHAR_NUM,   # 9
            CHAR_CHAR,  # colon
            CHAR_CHAR,  # semiclon
            CHAR_OP2,   # <
            CHAR_OP2,   # =
            CHAR_OP2,   # >
            CHAR_NONE,  # ?   BEEP BEEP
            CHAR_VAR,   # @
            CHAR_WORD,  # A
            CHAR_WORD,  # @
            CHAR_WORD,  # @
            CHAR_WORD,  # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # Z
            CHAR_CHAR,            # [
            CHAR_BACK,
            CHAR_CHAR,            # ]
            CHAR_OP1, # ^
            CHAR_WORD,             # _
            CHAR_WORD,             # backtick
            CHAR_WORD,            # A
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # @
            CHAR_WORD,            # z
            CHAR_CHAR,            # 123 { left brace
            CHAR_OP2,             # 124 | pipe
            CHAR_CHAR,            # 125 } right brace
            CHAR_OP1,             # 126  ~
            CHAR_WHITE
]


keyword_phrases = dict({
        'IN': ('BOOLEAN',),
        'IN BOOLEAN': ('MODE',),
        'ALTER': ('DOMAIN', 'TABLE'),
        'IN BOOLEAN': ('MODE',),
        'GROUP': ('BY',),
        'ORDER': ('BY',),
        'OWN3D': ('BY',),
        'SELECT': ('ALL',),
        'READ': ('WRITE',),
        'LEFT': ('OUTER', 'JOIN'),
        'RIGHT': ('OUTER', 'JOIN'),
        'FULL': ('OUTER',),
        'CROSS': ('JOIN'),
        'NATURAL': ('JOIN','INNER', 'OUTER','LEFT', 'RIGHT', 'FULL')
        })

operator_phrases = dict({
        'SOUNDS': ('LIKE',),
        'IS': ('NOT',),
        'NOT': ('LIKE', 'BETWEEN', 'SIMILAR', 'IN'),
        'SIMILAR': ('TO',),
        'NOT SIMILAR': ('TO',),
        'UNION': ('ALL',),
        'INTERSECT': ('ALL',)     # oracle
        })
